# Generated by Django 3.1.2 on 2020-10-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20201019_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Opção', 'verbose_name_plural': 'Opções'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('pub_date',), 'verbose_name': 'Questão', 'verbose_name_plural': 'Questões'},
        ),
        migrations.AddField(
            model_name='question',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Publicados'),
        ),
    ]
